begin;

create table if not exists public.attendance_work_sessions (
  id            bigint generated by default as identity primary key,
  record_id     bigint not null references public.attendance_records(id) on delete cascade,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  work_date     date not null,
  started_at    timestamptz not null,
  ended_at      timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint attendance_work_sessions_end_after_start
    check (ended_at is null or ended_at >= started_at)
);

create index if not exists idx_attendance_work_sessions_record
  on public.attendance_work_sessions(record_id);

create index if not exists idx_attendance_work_sessions_user_date
  on public.attendance_work_sessions(user_id, work_date desc, started_at desc);

create unique index if not exists uq_attendance_work_sessions_open_record
  on public.attendance_work_sessions(record_id)
  where ended_at is null;

create or replace function public.set_attendance_work_sessions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_work_sessions_updated_at on public.attendance_work_sessions;
create trigger trg_attendance_work_sessions_updated_at
before update on public.attendance_work_sessions
for each row execute function public.set_attendance_work_sessions_updated_at();

alter table public.attendance_work_sessions enable row level security;

drop policy if exists "Users can read own or admin all attendance work sessions" on public.attendance_work_sessions;
drop policy if exists "Users can insert own or admin all attendance work sessions" on public.attendance_work_sessions;
drop policy if exists "Users can update own or admin all attendance work sessions" on public.attendance_work_sessions;
drop policy if exists "Admins can delete attendance work sessions" on public.attendance_work_sessions;

create policy "Users can read own or admin all attendance work sessions"
  on public.attendance_work_sessions for select
  using (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Users can insert own or admin all attendance work sessions"
  on public.attendance_work_sessions for insert
  with check (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Users can update own or admin all attendance work sessions"
  on public.attendance_work_sessions for update
  using (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  )
  with check (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Admins can delete attendance work sessions"
  on public.attendance_work_sessions for delete
  using (public.is_admin());

commit;
