-- 2026-03-10
-- 근태관리 Phase 2
-- 목적:
-- 1) 근무 기준 설정(attendance_settings)
-- 2) 휴가/반차 신청(leave_requests)

begin;

create table if not exists public.attendance_settings (
  id                    bigint generated by default as identity primary key,
  work_start_time       text not null default '09:00',
  work_end_time         text not null default '18:00',
  late_grace_minutes    integer not null default 10,
  early_leave_grace_minutes integer not null default 20,
  lunch_break_minutes   integer not null default 60,
  standard_work_minutes integer not null default 480,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint attendance_settings_time_format check (
    work_start_time ~ '^[0-2][0-9]:[0-5][0-9]$'
    and work_end_time ~ '^[0-2][0-9]:[0-5][0-9]$'
  )
);

insert into public.attendance_settings (
  id,
  work_start_time,
  work_end_time,
  late_grace_minutes,
  early_leave_grace_minutes,
  lunch_break_minutes,
  standard_work_minutes
)
values (1, '09:00', '18:00', 10, 20, 60, 480)
on conflict (id) do nothing;

create or replace function public.set_attendance_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_settings_updated_at on public.attendance_settings;
create trigger trg_attendance_settings_updated_at
before update on public.attendance_settings
for each row execute function public.set_attendance_settings_updated_at();

create table if not exists public.attendance_work_sessions (
  id            bigint generated by default as identity primary key,
  record_id     bigint not null references public.attendance_records(id) on delete cascade,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  work_date     date not null,
  started_at    timestamptz not null,
  ended_at      timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint attendance_work_sessions_end_after_start
    check (ended_at is null or ended_at >= started_at)
);

create index if not exists idx_attendance_work_sessions_record
  on public.attendance_work_sessions(record_id);

create index if not exists idx_attendance_work_sessions_user_date
  on public.attendance_work_sessions(user_id, work_date desc, started_at desc);

create unique index if not exists uq_attendance_work_sessions_open_record
  on public.attendance_work_sessions(record_id)
  where ended_at is null;

create or replace function public.set_attendance_work_sessions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_work_sessions_updated_at on public.attendance_work_sessions;
create trigger trg_attendance_work_sessions_updated_at
before update on public.attendance_work_sessions
for each row execute function public.set_attendance_work_sessions_updated_at();

create table if not exists public.leave_requests (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  leave_type    text not null,
  start_date    date not null,
  end_date      date not null,
  status        text not null default 'pending',
  reason        text,
  approved_by   uuid references public.profiles(id) on delete set null,
  approved_at   timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint leave_requests_type_check check (
    leave_type in ('annual', 'half_am', 'half_pm', 'sick', 'official', 'other')
  ),
  constraint leave_requests_status_check check (
    status in ('pending', 'approved', 'rejected')
  ),
  constraint leave_requests_date_check check (end_date >= start_date),
  constraint leave_requests_half_day_single check (
    leave_type not in ('half_am', 'half_pm') or start_date = end_date
  )
);

create index if not exists idx_leave_requests_user_date
  on public.leave_requests(user_id, start_date desc, end_date desc);

create index if not exists idx_leave_requests_status
  on public.leave_requests(status, start_date desc);

create or replace function public.set_leave_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_leave_requests_updated_at on public.leave_requests;
create trigger trg_leave_requests_updated_at
before update on public.leave_requests
for each row execute function public.set_leave_requests_updated_at();

alter table public.attendance_settings enable row level security;
alter table public.attendance_work_sessions enable row level security;
alter table public.leave_requests enable row level security;

drop policy if exists "All authenticated can read attendance settings" on public.attendance_settings;
drop policy if exists "Admins can manage attendance settings" on public.attendance_settings;

create policy "All authenticated can read attendance settings"
  on public.attendance_settings for select
  using (auth.role() = 'authenticated');

create policy "Admins can manage attendance settings"
  on public.attendance_settings for all
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Users can read own or admin all attendance work sessions" on public.attendance_work_sessions;
drop policy if exists "Users can insert own or admin all attendance work sessions" on public.attendance_work_sessions;
drop policy if exists "Users can update own or admin all attendance work sessions" on public.attendance_work_sessions;
drop policy if exists "Admins can delete attendance work sessions" on public.attendance_work_sessions;

create policy "Users can read own or admin all attendance work sessions"
  on public.attendance_work_sessions for select
  using (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Users can insert own or admin all attendance work sessions"
  on public.attendance_work_sessions for insert
  with check (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Users can update own or admin all attendance work sessions"
  on public.attendance_work_sessions for update
  using (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  )
  with check (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Admins can delete attendance work sessions"
  on public.attendance_work_sessions for delete
  using (public.is_admin());

drop policy if exists "Users can read own or admin all leave requests" on public.leave_requests;
drop policy if exists "Users can insert own leave requests" on public.leave_requests;
drop policy if exists "Admins can update leave requests" on public.leave_requests;
drop policy if exists "Admins can delete leave requests" on public.leave_requests;

create policy "Users can read own or admin all leave requests"
  on public.leave_requests for select
  using (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Users can insert own leave requests"
  on public.leave_requests for insert
  with check (
    auth.role() = 'authenticated'
    and auth.uid() = user_id
  );

create policy "Admins can update leave requests"
  on public.leave_requests for update
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete leave requests"
  on public.leave_requests for delete
  using (public.is_admin());

commit;
