-- 2026-03-05
-- 근태관리 Phase 1
-- 목적:
-- 1) 사용자 출근/퇴근 기록 테이블 생성
-- 2) 본인 기록 입력 + 관리자 전체 관리 RLS 적용

begin;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and coalesce(status, 'active') = 'active'
  );
$$;

create table if not exists public.attendance_records (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  work_date     date not null,
  check_in_at   timestamptz,
  check_out_at  timestamptz,
  check_in_note text,
  check_out_note text,
  updated_by    uuid references public.profiles(id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint attendance_records_unique_user_day unique (user_id, work_date),
  constraint attendance_records_checkout_after_checkin
    check (check_out_at is null or (check_in_at is not null and check_out_at >= check_in_at))
);

create index if not exists idx_attendance_records_user_date
  on public.attendance_records(user_id, work_date desc);

create index if not exists idx_attendance_records_work_date
  on public.attendance_records(work_date desc);

create or replace function public.set_attendance_records_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_records_updated_at on public.attendance_records;
create trigger trg_attendance_records_updated_at
before update on public.attendance_records
for each row execute function public.set_attendance_records_updated_at();

alter table public.attendance_records enable row level security;

drop policy if exists "Users can read own or admin all attendance records" on public.attendance_records;
drop policy if exists "Users can insert own attendance records" on public.attendance_records;
drop policy if exists "Users can update own or admin all attendance records" on public.attendance_records;
drop policy if exists "Admins can delete attendance records" on public.attendance_records;

create policy "Users can read own or admin all attendance records"
  on public.attendance_records for select
  using (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Users can insert own attendance records"
  on public.attendance_records for insert
  with check (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Users can update own or admin all attendance records"
  on public.attendance_records for update
  using (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  )
  with check (
    auth.role() = 'authenticated'
    and (
      auth.uid() = user_id
      or public.is_admin()
    )
  );

create policy "Admins can delete attendance records"
  on public.attendance_records for delete
  using (public.is_admin());

commit;
